@baseUrl = http://localhost:3333

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}
> {%
  client.global.set("token", response.body.access_token);
%}

### Me (JWT)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
