@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbW13MzNzNm8wMDAwemg1Znh2eHh4Y243IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NDAxNTc5OCwiZXhwIjoxNzc0MTAyMTk4fQ.i1-Uk0rPXGUiTjQSIusAqsAufXKoH8dSNnge6YB2Xbo
@fileId = cmmw473dj0001zhhpv6ndvo7y

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

> {%
  client.log(JSON.stringify(response.body));
  client.global.set("token", response.body.accessToken);
%}

### Upload XML
# @name upload
POST {{baseUrl}}/files/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file1.xml"
Content-Type: application/xml

< ./XML/file1.xml
--WebAppBoundary--

### List files
GET {{baseUrl}}/files
Authorization: Bearer {{token}}

### Analyze XML by file id
GET {{baseUrl}}/files/{{fileId}}/analysis
Authorization: Bearer {{token}}

### Download by id
GET {{baseUrl}}/files/{{fileId}}/download
Authorization: Bearer {{token}}
